### ISSUE TITLE
requirements.txt

### ISSUE THREAD

**Issue by arilamstein** [sfbrigade/datasci-earthquake#1]
I just cloned the repo and typed:

```
streamlit run app.py
```

and get:

```
2024-07-24 19:12:01.144 Uncaught app exception
Traceback (most recent call last):
  File "/Users/arilamstein/python/venv/lib/python3.11/site-packages/streamlit/runtime/scriptrunner/script_runner.py", line 535, in _run_script
    exec(code, module.__dict__)
  File "/Users/arilamstein/python/datasci-earthquake/app.py", line 3, in <module>
    from streamlit_folium import st_folium
ModuleNotFoundError: No module named 'streamlit_folium'
```

I'm not an expert in python, but I think that most repos have a file called [requirements.txt](https://www.freecodecamp.org/news/python-requirementstxt-explained/) that lists all the packages needed to be installed to run the app. Perhaps we could add one so that it's easy for people to run the app?

**Comment by arilamstein** [comment]
From a discussion during the meetup it sounds like this project does not require `requirements.txt` (although I think it would if you wanted to deploy it on Streamlit's Community Cloud). But perhaps updating the README to have installation instructions would be helpful.
